name: tripwonder
description: "A new Flutter project."


publish_to: 'none' 



version: 1.0.0+1

environment:
  sdk: ^3.5.3







dependencies:
  flutter:
    sdk: flutter


  
  
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  firebase_core: ^2.27.1
  firebase_auth: ^4.17.9
  firebase_storage: ^11.6.10
  firebase_analytics: ^10.8.10
  get_it: ^7.6.7
  image_picker: ^1.0.7
  flutter_native_splash: ^2.4.1
  iconsax: ^0.0.8
  get: ^4.6.5
  intl: ^0.19.0
  carousel_slider: ^5.0.0
  url_launcher: ^6.3.0
  flutter_rating_bar: ^4.0.1
  readmore: ^3.0.0
  google_maps_flutter: ^2.9.0
  http: ^1.2.2
  google_sign_in: ^6.2.1
  dio: ^5.7.0
  flutter_polyline_points: ^2.1.0
  location: ^5.0.0
  geolocator: ^12.0.0
  firebase_messaging: ^14.9.4
  flutter_local_notifications: ^17.2.4
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  
  
  
  
  
  flutter_lints: ^4.0.0





flutter:

  
  
  
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/vectors/
    - assets/logos/
    - assets/banner/
    - assets/images/user.png
  
  
  
  
  
  
  
  
  
  
  
  
